# Generated by Django 3.2.7 on 2021-09-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'Dashboard'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='user.userdetails'),
        ),
    ]
