# Generated by Django 3.2.7 on 2021-09-24 13:14

from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210923_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skill'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(upload_to=user.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='about_image',
            field=models.ImageField(upload_to=user.models.path_and_rename, validators=[user.models.validate_image], verbose_name='About Image'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact_me_new_project_image',
            field=models.ImageField(upload_to=user.models.path_and_rename, verbose_name='Contact me image'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='cv_in_pdf',
            field=models.FileField(help_text='.pdf allowed only', upload_to=user.models.path_and_rename, validators=[user.models.validate_pdf], verbose_name='Resume/CV'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Qualification Name')),
                ('from_to_year', models.CharField(help_text='2017-2019', max_length=20, verbose_name='From to year')),
                ('institute', models.CharField(help_text='Delhi, JNU', max_length=256, verbose_name='Institute')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='user.userdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
